# Import libraries

In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Read dataset 1

In [62]:
dataset = pd.read_csv("H:\My document 2.0\Thesis\Final\Foodborne-diseases-prediction-main\outbreaks.csv")

In [63]:
dataset.head()

Year    Month       State                Location  \
0  1998  January  California              Restaurant   
1  1998  January  California                     NaN   
2  1998  January  California              Restaurant   
3  1998  January  California              Restaurant   
4  1998  January  California  Private Home/Residence   

                                Food Ingredient              Species  \
0                                NaN        NaN                  NaN   
1                            Custard        NaN                  NaN   
2                                NaN        NaN                  NaN   
3                          Fish, Ahi        NaN      Scombroid toxin   
4  Lasagna, Unspecified; Eggs, Other        NaN  Salmonella enterica   

  Serotype/Genotype     Status  Illnesses  Hospitalizations  Fatalities  
0               NaN        NaN         20               0.0         0.0  
1               NaN        NaN        112               0.0         0.0  
2               NaN        NaN         35               0.0         0.0  
3               NaN  Confirmed          4               0.0         0.0  
4       Enteritidis  Confirmed         26               3.0         0.0

# Check null value

In [64]:
dataset.isnull().sum()

Year                     0
Month                    0
State                    0
Location              2166
Food                  8963
Ingredient           17243
Species               6619
Serotype/Genotype    15212
Status                6619
Illnesses                0
Hospitalizations      3625
Fatalities            3601
dtype: int64

In [65]:
e = dataset.dropna()

In [66]:
e

Year      Month        State                Location  \
638    1998       June     New York  Private Home/Residence   
669    1998       July      Arizona              Restaurant   
955    1998  September     Maryland              Restaurant   
1319   1999    January   California              Restaurant   
1321   1999    January   California              Restaurant   
...     ...        ...          ...                     ...   
19012  2015   November    Tennessee              Restaurant   
19014  2015   November         Utah        Catering Service   
19045  2015   December  Connecticut              Restaurant   
19068  2015   December     Michigan  Private Home/Residence   
19081  2015   December   Multistate  Private Home/Residence   

                                           Food           Ingredient  \
638                        Chicken, Unspecified              Chicken   
669                              Chile Rellenos                  Egg   
955               Multiple Cheeses, Unspecified               Cheese   
1319                              Eggs Benedict                  Egg   
1321   Chile Relleno, Unspecified; Rice, Yellow             Egg; Egg   
...                                         ...                  ...   
19012                                 Hamburger          Ground Beef   
19014                           Eggs, Scrambled                  Egg   
19045                                 Cucumbers             Cucumber   
19068                                      Cake       Frosting/Icing   
19081                   Powder Meal Replacement  Moringa Leaf Powder   

                                       Species       Serotype/Genotype  \
638                        Salmonella enterica             Typhimurium   
669                        Salmonella enterica             Enteritidis   
955                     Norovirus genogroup II                 Unknown   
1319                       Salmonella enterica             Enteritidis   
1321                       Salmonella enterica             Enteritidis   
...                                        ...                     ...   
19012  Escherichia coli, Shiga toxin-producing                 O157:H7   
19014                      Salmonella enterica             Enteritidis   
19045                      Salmonella enterica                Thompson   
19068                   Norovirus genogroup II  GII_17 Kawasaki (2014)   
19081                      Salmonella enterica                 Virchow   

          Status  Illnesses  Hospitalizations  Fatalities  
638    Confirmed          4               3.0         0.0  
669    Confirmed         58              11.0         0.0  
955    Confirmed        258               4.0         0.0  
1319   Confirmed          3               0.0         0.0  
1321   Confirmed         31               6.0         0.0  
...          ...        ...               ...         ...  
19012  Confirmed         13               0.0         0.0  
19014  Confirmed          3               0.0         0.0  
19045  Confirmed          3               0.0         0.0  
19068  Confirmed         73               0.0         0.0  
19081  Confirmed         35               6.0         0.0  

[420 rows x 12 columns]

In [67]:
e.shape

(420, 12)

# Read dataset 2

In [68]:
fooddata = pd.read_csv("H:\My document 2.0\Thesis\Final\Foodborne-diseases-prediction-main\FoodData.csv")

In [69]:
fooddata.head()

Year  Month      State Genus Species Serotype or Genotype Etiology Status  \
0  2009      1  Minnesota     Norovirus                  NaN       Suspected   
1  2009      1  Minnesota     Norovirus                  NaN       Confirmed   
2  2009      1  Minnesota     Norovirus                  NaN       Suspected   
3  2009      1  Minnesota     Norovirus                  NaN       Confirmed   
4  2009      1  Minnesota     Norovirus                  NaN       Confirmed   

                             Location of Preparation  Illnesses  \
0                       Restaurant - Sit-down dining          2   
1                                                NaN         16   
2                       Restaurant - Sit-down dining          5   
3  Restaurant - "Fast-food"(drive up service or p...          3   
4                 Restaurant - other or unknown type         21   

   Hospitalizations  Deaths Food Vehicle Contaminated Ingredient  
0               0.0     0.0          NaN                     NaN  
1               0.0     0.0          NaN                     NaN  
2               0.0     0.0          NaN                     NaN  
3               0.0     0.0          NaN                     NaN  
4               0.0     0.0      cookies                     NaN

# Check null value 

In [70]:
f = fooddata.isnull().sum()
f

Year                           0
Month                          0
State                          0
Genus Species               6619
Serotype or Genotype       15212
Etiology Status             6619
Location of Preparation     1135
Illnesses                      0
Hospitalizations            3625
Deaths                      3601
Food Vehicle                8963
Contaminated Ingredient    17243
dtype: int64

In [71]:
f = fooddata.dropna()
f.shape

(459, 12)

# Extracting variables

In [72]:
X = dataset.drop(['Year','Month','State','Serotype/Genotype','Status','Hospitalizations','Fatalities'], axis = 1)
y = dataset['Status']

# data preprocessing

In [73]:
from sklearn import preprocessing
le_x = preprocessing.LabelEncoder()
X.Location = le_x.fit_transform(X.Location)
X.Food = le_x.fit_transform(X.Food)
X.Ingredient = le_x.fit_transform(X.Ingredient)
X.Species = le_x.fit_transform(X.Species)
y = le_x.fit_transform(y)

In [74]:
X

Location  Food  Ingredient  Species  Illnesses
0            98  3127         381      201         20
1           161   860         381      201        112
2            98  3127         381      201         35
3            98  1034         381      162          4
4            65  1518         381      133         26
...         ...   ...         ...      ...        ...
19114        98  3127         381      107          4
19115        65  2364         381      107         16
19116        55  3127         381      107         43
19117        30  3127         381      107          5
19118       161  3127         381      201          3

[19119 rows x 5 columns]

In [75]:
y

array([22, 22, 22, ...,  0,  0, 22])

# Train & test the dataset

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 1)

# Scaling

In [77]:
from sklearn.preprocessing import StandardScaler
st_X = StandardScaler()
X_train = st_X.fit_transform(X_train)
X_test = st_X.transform(X_test)

# apply random forest

In [78]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10, criterion = "entropy")
#rfc_pred = rfc.predict(X_test)
rfc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [79]:
prediction_rfc = rfc.predict(X_test)
prediction_rfc

array([ 0,  0,  0, ..., 22, 22,  0])

In [80]:
rfc.score(X_test,y_test)

0.8111924686192469

# apply decision tree

In [81]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [82]:
prediction_d = dtree.predict(X_test)
prediction_d

array([ 0, 13, 13, ..., 22, 22,  0])

In [83]:
dtree.score(X_test,y_test)

0.803347280334728

# apply logistic

In [84]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [85]:
prediction_c = classifier.predict(X_test)
prediction_c

array([13,  0,  0, ..., 22, 22,  0])

In [86]:
classifier.score(X_test, y_test)

0.7606345885634589

In [87]:
from sklearn.metrics import classification_report, confusion_matrix

In [88]:
print(classification_report(y_test,prediction_c))

              precision    recall  f1-score   support

           0       0.65      0.98      0.78      2371
           1       0.00      0.00      0.00        41
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         1
           9       0.00      0.00      0.00        10
          10       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         2
          13       0.60      0.06      0.11      1241
          14       0.00      0.00      0.00         3
          16       0.00      0.00      0.00        90
          19       0.00      0.00      0.00         1
          22       0.96      1.00      0.98      1968

    accuracy                           0.76      5736
   macro avg       0.16      0.15      0.13      5736
weighted avg       0.73      0.76      0.68      5736



C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo